### ISSUE TITLE
请问现在这个项目还能用吗，我的提示了版本过低

### ISSUE THREAD

**Issue by Liumh32** [ProtobufBot/Spring-Mirai-Client#16]
现在报了这个问题

Exception in thread "DefaultDispatcher-worker-3" net.mamoe.mirai.network.WrongPasswordException: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo= )
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:186)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

![image](https://user-images.githubusercontent.com/48045684/102980093-faeda080-4541-11eb-8e5c-842cd604ec6c.png)

**Comment by lz1998** [comment]
有些人可以用，有些人不能用，因为近期QQ协议更新了，以后会更新到mirai2.0，现在可以先用go-mirai-client

https://github.com/protobufbot/go-Mirai-Client

交流群号：335783090

**Comment by lz1998** [comment]
> 现在报了这个问题
> 
> Exception in thread "DefaultDispatcher-worker-3" net.mamoe.mirai.network.WrongPasswordException: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo= )
> at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:186)
> at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
> at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
> at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
> at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
> at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
> at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
> at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
> at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
> at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
> 
> ![image](https://user-images.githubusercontent.com/48045684/102980093-faeda080-4541-11eb-8e5c-842cd604ec6c.png)

[GMC](https://github.com/protobufbot/go-Mirai-Client)已解决这个问题，建议暂时使用这个，不需要任何环境，exe文件可直接运行。

JVM的Spring版本需要等mirai官方处理后解决

**Comment by lz1998** [comment]
Spring-Mirai-Client 最新版已解决这个问题（0.0.14），协议已更新到mirai2.0

不过还是更建议用[gmc](https://github.com/ProtobufBot/Go-Mirai-Client/releases)，因为更稳定，性能更好
